apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nodejs-mongo-persistent.fullname" . }}
  labels:
    {{- include "nodejs-mongo-persistent.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storage | default "1Gi" }}