apiVersion: v1
data:
  database-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  database-password: {{ randAlphaNum 10 | b64enc | quote }}
  database-user: {{ randAlphaNum 5 | b64enc | quote }}
kind: Secret
metadata:
  labels:
    {{- include "nodejs-mongo-persistent.labels" . | nindent 4 }}
  name: {{ include "nodejs-mongo-persistent.fullname" . }}
type: Opaque