{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodejs-mongo-persistent.serviceAccountName" . }}
  labels:
{{ include "nodejs-mongo-persistent.labels" . | nindent 4 }}
{{- end -}}
