apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-mongo-persistent.fullname" . }}-mongo
  labels:
    {{- include "nodejs-mongo-persistent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: 27017
      targetPort: http
      protocol: TCP
      name: mongo
  selector:
    {{- include "nodejs-mongo-persistent.selectorLabels" . | nindent 4 }}
