apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tutorial-crud-api.fullname" . }}
  labels:
    {{- include "tutorial-crud-api.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storage | default "1Gi" }}