{{- if .Values.route.enabled -}}
{{- $fullName := include "tutorial-crud-api.fullname" . -}}
{{- $svcPort := .Values.nodejs.service.port -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: {{ $fullName }}
  labels:
    {{- include "tutorial-crud-api.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host | quote }}
  port:
    targetPort: {{ .Values.route.targetPort | default "8080-tcp" }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
{{ end }}
