apiVersion: v1
data:
  database-admin-password: {{ "password" | b64enc | quote }}
  database-password: {{  "password"  | b64enc | quote }}
  database-user: {{  "user"  | b64enc | quote }}
kind: Secret
metadata:
  labels:
    {{- include "tutorial-crud-api.labels" . | nindent 4 }}
  name: {{ include "tutorial-crud-api.fullname" . }}
type: Opaque