apiVersion: v1
kind: Service
metadata:
  name: {{ include "tutorial-crud-api.fullname" . }}-mongo
  labels:
    {{- include "tutorial-crud-api.labels" . | nindent 4 }}
    {{- include "tutorial-crud-api.labels.backend" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    {{- include "tutorial-crud-api.selectorLabels" . | nindent 4 }}
    {{- include "tutorial-crud-api.selectorLabels.backend" . | nindent 4 }}
