{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
{{ include "postgres.labels" . | indent 4 }}
{{- if .Values.postgres.labels }}
{{ toYaml .Values.postgres.labels | indent 4 }}
{{- end }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.statefulset.enabled }}
  serviceName: {{ template "postgres.fullname" . }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy:
{{ toYaml .Values.deploymentStrategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "postgres.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
    {{- if .Values.postgres.podAnnotations }}
      annotations:
{{ toYaml .Values.postgres.podAnnotations | indent 8}}
    {{- end }}
      labels:
        app: {{ template "postgres.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.deployment.initContainers }}
      initContainers:
{{ toYaml .Values.deployment.initContainers | indent 6 }}
      {{- end }}
      {{- if .Values.postgres.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.postgres.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.postgres.hostAliases }}
      hostAliases:
{{ toYaml .Values.postgres.hostAliases | indent 8 }}
      {{- end }}
      {{- if .Values.postgres.imagePullSecret }}
      imagePullSecrets:
        - name: {{ template "postgres.name" . }}
      {{- end }}
      containers:
        - name: postgres
          image: {{ .Values.postgres.imageName }}
          imagePullPolicy: {{ .Values.postgres.imagePullPolicy }}
          lifecycle:
          {{- if .Values.deployment.postStart.command }}
            postStart:
              exec:
                command: {{ .Values.deployment.postStart.command }}
          {{- end }}
          {{- if .Values.deployment.preStart.command }}
            preStart:
              exec:
                command: {{ .Values.deployment.preStart.command }}
          {{- end }}
          env:
{{ toYaml .Values.postgres.env | indent 12 }}
          resources:
{{ toYaml .Values.postgres.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.postgres.postgresPort }}
              name: postgres
          livenessProbe:
{{ toYaml .Values.postgres.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.postgres.readinessProbe | indent 12 }}
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: {{ template "postgres.fullname" . }}-data
            {{- if .Values.deployment.additionalVolumeMounts}}
{{ toYaml .Values.deployment.additionalVolumeMounts | indent 12 }}
            {{- end }}
        {{- if .Values.deployment.additionalContainers }}
{{ toYaml .Values.deployment.additionalContainers | indent 8 }}
        {{- end }}
      {{- if .Values.postgres.securityContext }}
      securityContext:
{{ toYaml .Values.postgres.securityContext | indent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.statefulset.enabled }}
        {{- if not .Values.persistence.enabled }}
        - name: {{ template "postgres.fullname" . }}-data
          emptyDir: {}
        {{- end }}
        - name: {{ template "postgres.fullname" . }}-backup
          emptyDir: {}
        {{- else }}
        - name: {{ template "postgres.fullname" . }}-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-%s" (include "postgres.fullname" .) "data") }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: {{ template "postgres.fullname" . }}-backup
          emptyDir: {}
        {{- end }}
        {{- if .Values.config.enabled }}
        - name: {{ template "postgres.name" . }}-conf
          configMap:
            name: {{ template "postgres.name" . }}-conf
        {{- end }}
        {{- if .Values.secret.enabled }}
        - name: {{ template "postgres.name" . }}-secret
          secret:
            secretName: {{ template "postgres.name" . }}-secret
        {{- end }}
        {{- if .Values.deployment.additionalVolumes }}
{{ toYaml .Values.deployment.additionalVolumes | indent 8 }}
        {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}


## create pvc in case of statefulsets
  {{- if .Values.statefulset.enabled }}
  volumeClaimTemplates:
    {{- if .Values.persistence.enabled }}
    - metadata:
        name: {{ template "postgres.fullname" . }}-data
        labels:
{{ include "postgres.labels" . | indent 10 }}
        {{- if .Values.persistence.annotations }}
        annotations:
{{ toYaml .Values.persistence.annotations | indent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.storageSize | quote }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
    {{- end }}
  {{- end }}
