apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.name" . }}-secret
  labels:
{{ include "postgres.labels" . | indent 4 }}
{{- if .Values.postgres.labels }}
{{ toYaml .Values.postgres.labels | indent 4 }}
{{- end }}
data:
{{ toYaml .Values.secret.data | indent 2 }}