---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-setup
  labels:
    app: postgres-setup
---
apiVersion: v1
kind: ConfigMap
data:
  my-file.sql: |-
    {{- include "config-sqlscript" . | indent 4 }}
metadata:
  name: postgressetup
  labels:
    app: postgres-setup
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-setup
  labels:
    app: postgres-setup
spec:
  backoffLimit: 50
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: postgres-setup-job
    spec:
      restartPolicy: OnFailure
      serviceAccountName: postgres-setup
      containers:
      - env:
        - name: SQLSCRIPT
          value: /opt/scripts/my-file.sql
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: postgres-secret
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: postgres-secret
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: postgres-secret
        - name: PGHOST
          value: postgres-service
        - name: PGPORT
          value: "5432"
        name: run-sqlscript
        image: quay.io/swinches/nodejs-runsqlscript:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /opt/scripts
          name: sql-script
      volumes:
      - name: sql-script
        configMap:
          name: postgressetup